// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzueAZIZHTzUnrhhDO6JR2s8tb6S3GNek',
    appId: '1:784525489483:web:9978872c1f235fd56924ce',
    messagingSenderId: '784525489483',
    projectId: 'freshpourproject',
    authDomain: 'freshpourproject.firebaseapp.com',
    storageBucket: 'freshpourproject.firebasestorage.app',
    measurementId: 'G-N5QWJZ6GLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR3qiIm2djSlQHiibjchWFLQnxC54XUJ4',
    appId: '1:784525489483:android:9594b896fc6ff8ef6924ce',
    messagingSenderId: '784525489483',
    projectId: 'freshpourproject',
    storageBucket: 'freshpourproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5arxMfNMGixbj0oJl2fVY9fKJd_f-Fxs',
    appId: '1:784525489483:ios:62b57ec8a069bcf16924ce',
    messagingSenderId: '784525489483',
    projectId: 'freshpourproject',
    storageBucket: 'freshpourproject.firebasestorage.app',
    iosBundleId: 'com.example.dairyproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5arxMfNMGixbj0oJl2fVY9fKJd_f-Fxs',
    appId: '1:784525489483:ios:62b57ec8a069bcf16924ce',
    messagingSenderId: '784525489483',
    projectId: 'freshpourproject',
    storageBucket: 'freshpourproject.firebasestorage.app',
    iosBundleId: 'com.example.dairyproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzueAZIZHTzUnrhhDO6JR2s8tb6S3GNek',
    appId: '1:784525489483:web:bd399a9a826678106924ce',
    messagingSenderId: '784525489483',
    projectId: 'freshpourproject',
    authDomain: 'freshpourproject.firebaseapp.com',
    storageBucket: 'freshpourproject.firebasestorage.app',
    measurementId: 'G-V6QCWKBJQY',
  );
}
